import { OverlayConfig } from './types';

export interface OverlayPreset {
  id: string;
  name: string;
  description: string;
  config: OverlayConfig;
}

export const PRESETS: OverlayPreset[] = [
  {
    id: 'single-spotlight',
    name: 'Single Market Spotlight',
    description: 'One large market widget centered with Kalshi branding',
    config: {
      width: 1920,
      height: 1080,
      background: { type: 'solid', color: 'rgba(0,0,0,0.75)' },
      elements: [
        {
          id: 'preset_shape_1',
          type: 'shape',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          zIndex: 0,
          props: { type: 'shape', shapeType: 'rectangle', color: 'rgba(0,0,0,0.75)', opacity: 1, borderRadius: 0, borderWidth: 0, borderColor: 'transparent' },
        },
        {
          id: 'preset_market_1',
          type: 'market',
          x: 660,
          y: 400,
          width: 600,
          height: 200,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#00DD94' },
        },
        {
          id: 'preset_logo_1',
          type: 'logo',
          x: 1720,
          y: 1000,
          width: 150,
          height: 50,
          zIndex: 10,
          props: { type: 'logo', variant: 'wordmark', color: '#28CC95', opacity: 0.8 },
        },
      ],
    },
  },
  {
    id: 'corner-widget',
    name: 'Corner Widget',
    description: 'Small market display in the bottom-right corner',
    config: {
      width: 1920,
      height: 1080,
      background: { type: 'transparent' },
      elements: [
        {
          id: 'preset_market_1',
          type: 'market',
          x: 1420,
          y: 860,
          width: 460,
          height: 180,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#00DD94' },
        },
        {
          id: 'preset_logo_1',
          type: 'logo',
          x: 1770,
          y: 810,
          width: 110,
          height: 36,
          zIndex: 10,
          props: { type: 'logo', variant: 'wordmark', color: '#28CC95', opacity: 0.7 },
        },
      ],
    },
  },
  {
    id: 'bottom-ticker',
    name: 'Bottom Ticker Bar',
    description: 'Horizontal bar of markets along the bottom',
    config: {
      width: 1920,
      height: 1080,
      background: { type: 'transparent' },
      elements: [
        {
          id: 'preset_shape_1',
          type: 'shape',
          x: 0,
          y: 920,
          width: 1920,
          height: 160,
          zIndex: 0,
          props: { type: 'shape', shapeType: 'rectangle', color: 'rgba(0,0,0,0.85)', opacity: 1, borderRadius: 0, borderWidth: 0, borderColor: 'transparent' },
        },
        {
          id: 'preset_market_1',
          type: 'market',
          x: 30,
          y: 935,
          width: 440,
          height: 130,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'compact', pollInterval: 30, showTitle: true, showVolume: false, accentColor: '#00DD94' },
        },
        {
          id: 'preset_market_2',
          type: 'market',
          x: 500,
          y: 935,
          width: 440,
          height: 130,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'compact', pollInterval: 30, showTitle: true, showVolume: false, accentColor: '#00DD94' },
        },
        {
          id: 'preset_market_3',
          type: 'market',
          x: 970,
          y: 935,
          width: 440,
          height: 130,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'compact', pollInterval: 30, showTitle: true, showVolume: false, accentColor: '#00DD94' },
        },
        {
          id: 'preset_logo_1',
          type: 'logo',
          x: 1770,
          y: 975,
          width: 110,
          height: 36,
          zIndex: 10,
          props: { type: 'logo', variant: 'wordmark', color: '#28CC95', opacity: 0.7 },
        },
      ],
    },
  },
  {
    id: 'head-to-head',
    name: 'Head to Head',
    description: 'Two markets side by side for versus matchups',
    config: {
      width: 1920,
      height: 1080,
      background: { type: 'solid', color: 'rgba(0,0,0,0.8)' },
      elements: [
        {
          id: 'preset_shape_1',
          type: 'shape',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          zIndex: 0,
          props: { type: 'shape', shapeType: 'rectangle', color: 'rgba(0,0,0,0.8)', opacity: 1, borderRadius: 0, borderWidth: 0, borderColor: 'transparent' },
        },
        {
          id: 'preset_text_1',
          type: 'text',
          x: 560,
          y: 200,
          width: 800,
          height: 80,
          zIndex: 2,
          props: { type: 'text', text: 'WHO WINS?', fontSize: 56, fontWeight: 800, color: '#ffffff', textAlign: 'center', backgroundColor: 'transparent', padding: 8, borderRadius: 0 },
        },
        {
          id: 'preset_market_1',
          type: 'market',
          x: 160,
          y: 380,
          width: 700,
          height: 300,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#3B82F6' },
        },
        {
          id: 'preset_text_vs',
          type: 'text',
          x: 885,
          y: 470,
          width: 150,
          height: 60,
          zIndex: 3,
          props: { type: 'text', text: 'VS', fontSize: 40, fontWeight: 800, color: '#9ca3af', textAlign: 'center', backgroundColor: 'transparent', padding: 8, borderRadius: 0 },
        },
        {
          id: 'preset_market_2',
          type: 'market',
          x: 1060,
          y: 380,
          width: 700,
          height: 300,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#EF4444' },
        },
        {
          id: 'preset_logo_1',
          type: 'logo',
          x: 860,
          y: 950,
          width: 200,
          height: 60,
          zIndex: 10,
          props: { type: 'logo', variant: 'wordmark', color: '#28CC95', opacity: 0.6 },
        },
      ],
    },
  },
  {
    id: 'dashboard',
    name: 'Full Dashboard',
    description: 'Grid of 4 markets with title and branding',
    config: {
      width: 1920,
      height: 1080,
      background: { type: 'solid', color: '#0a0a0a' },
      elements: [
        {
          id: 'preset_shape_1',
          type: 'shape',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          zIndex: 0,
          props: { type: 'shape', shapeType: 'rectangle', color: '#0a0a0a', opacity: 1, borderRadius: 0, borderWidth: 0, borderColor: 'transparent' },
        },
        {
          id: 'preset_text_1',
          type: 'text',
          x: 60,
          y: 40,
          width: 600,
          height: 60,
          zIndex: 2,
          props: { type: 'text', text: 'LIVE MARKETS', fontSize: 40, fontWeight: 800, color: '#ffffff', textAlign: 'left', backgroundColor: 'transparent', padding: 8, borderRadius: 0 },
        },
        {
          id: 'preset_logo_1',
          type: 'logo',
          x: 1700,
          y: 45,
          width: 160,
          height: 50,
          zIndex: 10,
          props: { type: 'logo', variant: 'wordmark', color: '#28CC95', opacity: 0.8 },
        },
        {
          id: 'preset_market_1',
          type: 'market',
          x: 60,
          y: 140,
          width: 880,
          height: 420,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#00DD94' },
        },
        {
          id: 'preset_market_2',
          type: 'market',
          x: 980,
          y: 140,
          width: 880,
          height: 420,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#3B82F6' },
        },
        {
          id: 'preset_market_3',
          type: 'market',
          x: 60,
          y: 600,
          width: 880,
          height: 420,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#F59E0B' },
        },
        {
          id: 'preset_market_4',
          type: 'market',
          x: 980,
          y: 600,
          width: 880,
          height: 420,
          zIndex: 1,
          props: { type: 'market', ticker: '', marketUrl: '', variant: 'expanded', pollInterval: 30, showTitle: true, showVolume: true, accentColor: '#EF4444' },
        },
      ],
    },
  },
  {
    id: 'sports-broadcast',
    name: 'Sports Broadcast',
    description: 'Full sports graphic with matchup, live trades, QR code, and disclaimer',
    config: {
      width: 1920,
      height: 1080,
      background: { type: 'solid', color: '#0a0a0a' },
      elements: [
        {
          id: 'preset_bg',
          type: 'shape',
          x: 0, y: 0, width: 1920, height: 1080, zIndex: 0,
          props: { type: 'shape', shapeType: 'rectangle', color: '#0a0a0a', opacity: 1, borderRadius: 0, borderWidth: 0, borderColor: 'transparent' },
        },
        {
          id: 'preset_matchup',
          type: 'matchup',
          x: 50, y: 30, width: 750, height: 280, zIndex: 3,
          props: {
            type: 'matchup', ticker: '', marketUrl: '', pollInterval: 30,
            team1Name: 'SEA', team2Name: 'NE',
            team1Color: '#00DD94', team2Color: '#3B82F6',
            showOdds: true, showPayout: true, payoutWager: 100,
            variant: 'large', vsStyle: 'text',
          },
        },
        {
          id: 'preset_logo',
          type: 'logo',
          x: 1550, y: 30, width: 320, height: 80, zIndex: 10,
          props: { type: 'logo', variant: 'wordmark', color: '#ffffff', opacity: 1 },
        },
        {
          id: 'preset_qr',
          type: 'qr-code',
          x: 1700, y: 130, width: 170, height: 170, zIndex: 5,
          props: { type: 'qr-code', url: '', fgColor: '#000000', bgColor: '#ffffff', padding: 8, borderRadius: 8 },
        },
        {
          id: 'preset_feed',
          type: 'trade-feed',
          x: 50, y: 370, width: 550, height: 500, zIndex: 2,
          props: {
            type: 'trade-feed',
            ticker: '', marketUrl: '', pollInterval: 15, maxTrades: 5,
            showDot: true, headerText: 'Live Trade', headerColor: '#ffffff',
            dotColor: '#ef4444', amountColor: '#00DD94',
            outcomeMap: '{"SEA":"#00DD94","NE":"#3B82F6"}',
            fontSize: 40, lineSpacing: 1.4, showSide: false, useAcronyms: true,
          },
        },
        {
          id: 'preset_disclaimer',
          type: 'disclaimer',
          x: 50, y: 1020, width: 900, height: 40, zIndex: 1,
          props: {
            type: 'disclaimer',
            text: 'Restrictions and eligibility requirements apply. Event contract trading involves significant risk and is not appropriate for everyone. Please carefully consider if it\u2019s appropriate for you in light of your personal financial circumstances. Prices may not be live and are subject to change. See kalshi.com/regulatory for more information. Federally regulated event contract exchange. Users over the age of 18 are able to register and trade.',
            fontSize: 9, color: '#ffffff', opacity: 0.3,
          },
        },
      ],
    },
  },
];
