/** Shared Tailwind class strings for overlay editor form controls */
export const oe = {
  props: 'flex flex-col gap-2.5 mt-2.5',
  row: 'flex gap-2 items-center flex-wrap',
  field: 'flex flex-col gap-[3px] flex-1 min-w-0',
  fieldFull: 'flex flex-col gap-[3px] flex-1 min-w-0 basis-full',
  fieldLabel: 'text-[10px] font-medium uppercase tracking-[0.06em] text-text-muted',
  input: 'w-full rounded-md border border-dark-border-light bg-dark-elevated px-2.5 py-[7px] text-[13px] text-text-primary transition-[border-color] duration-150 focus:border-brand focus:outline-none',
  inputSm: 'w-[70px] shrink-0 rounded-md border border-dark-border-light bg-dark-elevated px-2.5 py-[7px] text-[13px] text-text-primary transition-[border-color] duration-150 focus:border-brand focus:outline-none',
  select: 'min-w-0 flex-1 cursor-pointer rounded-md border border-dark-border-light bg-dark-elevated px-2.5 py-[7px] text-[13px] text-text-primary focus:border-brand focus:outline-none',
  color: 'size-8 shrink-0 cursor-pointer rounded-md border border-dark-border-light bg-none p-0.5',
  checkbox: 'flex cursor-pointer items-center gap-[5px] whitespace-nowrap text-xs text-text-secondary [&_input]:accent-brand',
  btn: 'cursor-pointer rounded-md border border-dark-border-light bg-dark-elevated px-3.5 py-2 text-[13px] font-medium text-text-primary transition-[background,border-color] duration-150 hover:border-[#444] hover:bg-dark-border-light',
  btnPrimary: 'w-full cursor-pointer rounded-md border border-brand bg-brand px-3.5 py-2 text-[13px] font-semibold text-black transition-[background,border-color] duration-150 hover:border-[#0ad690] hover:bg-[#0ad690]',
  btnSm: 'shrink-0 cursor-pointer rounded-md border border-dark-border-light bg-dark-elevated px-2.5 py-1.5 text-xs font-medium text-text-primary transition-[background,border-color] duration-150 hover:border-[#444] hover:bg-dark-border-light',
  section: 'border-b border-dark-border px-4 py-4',
  label: 'mb-2.5 block text-[11px] font-semibold uppercase tracking-[0.08em] text-text-secondary',
  presetGrid: 'flex flex-wrap gap-1.5',
  presetBtn: 'cursor-pointer rounded-md border border-dark-border-light bg-dark-elevated px-2.5 py-1.5 text-xs text-text-primary transition-[background,border-color] duration-150 hover:border-brand hover:bg-dark-border-light',
  addGrid: 'flex flex-wrap gap-1.5',
  addBtn: 'flex cursor-pointer items-center gap-[5px] rounded-md border border-dark-border-light bg-dark-elevated px-2.5 py-[7px] text-xs text-text-primary transition-[background,border-color] duration-150 hover:border-brand hover:bg-dark-border-light hover:text-brand',
  layerList: 'flex flex-col gap-0.5',
  layerItem: 'flex cursor-pointer items-center gap-2 rounded-md px-2.5 py-2 text-[13px] transition-[background] duration-100 hover:bg-dark-elevated',
  layerItemSelected: 'bg-[#1e3a2e] outline outline-1 outline-[#09C28544]',
  layerItemDragover: '-mt-0.5 border-t-2 border-brand',
  layerItemDragging: 'opacity-40',
  layerGrip: 'shrink-0 cursor-grab select-none py-0.5 text-[10px] leading-none tracking-[-3px] text-[#4b5563] active:cursor-grabbing',
  layerType: 'shrink-0 rounded-[3px] bg-[#09C28515] px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-[0.06em] text-brand',
  layerDetail: 'flex-1 truncate text-xs text-text-secondary',
  layerActions: 'flex shrink-0 gap-0.5',
  layerBtn: 'cursor-pointer rounded-[3px] border-none bg-none px-1 py-0.5 text-[10px] leading-none text-text-muted transition-[color,background] duration-100 hover:bg-dark-border-light hover:text-text-primary',
  layerBtnDelete: 'cursor-pointer rounded-[3px] border-none bg-none px-1 py-0.5 text-[10px] leading-none text-text-muted transition-[color,background] duration-100 hover:bg-[#2a1a1a] hover:text-[#ef4444]',
  empty: 'py-2 text-[13px] text-text-muted',
} as const;
